[package]
name = "provisioner"
version = "0.1.0"
edition = "2021"

[dependencies]
subxt = { version = "0.33", features = ["substrate-compat"], default-features = true }
subxt-signer = { version = "0.33", features = [], default-features = true }
tokio = { version = "1.35", features = ["macros", "rt-multi-thread"], default-features = false }
scale = { package = "parity-scale-codec", version = "3.6", default-features = false, features = ["derive"] }
toml = { version = "0.8", features = ["parse", "display"], default-features = false }
serde = { version = "1.0", features = [], default-features = false }
clap = { version = "4.4", features = ["std", "derive", "help"], default-features = false }
contract-transcode = { version = "3.2.0", features = [], default-features = false }
pallet-contracts-primitives = { version = "29.0", features = [], default-features = false }
