[package]
name = "provisioner"
version = "0.1.0"
edition = "2021"

[dependencies]
subxt = { version = "0.33", features = [], default-features = true }
tokio = { version = "1.35", features = ["macros", "rt-multi-thread"], default-features = false }
scale = { package = "parity-scale-codec", version = "3.6", default-features = false, features = ["derive"] }
